language: java
install: true
jdk:
- openjdk8
env:
  global:
  - GPG_FILE_NAME="jcv_db_sign.gpg"
  - ENCRYPTED_GPG_FILE_NAME="jcv_db_sign.gpg.enc"
  - secure: jsW+7UV4JFY9gPGAkXW78MKZ5kcDwDu6crX0hVGADntaywEBDOtarioyD+xXPpAfwDEr/5c2wVl5G2/IWG7PwCOQ7TwcJuX4lL33MwbfdPMWupnjCtZ62nKz0ZkXDAjoqxSncOFgwA22anAh5ZV3ZICo5uwsMwuhZZ/gs+c8frGgQxL1t8MWqZ99T6S9JirS+fff+1q8Le5H9kaCPjC+4D3Qdj8yidFPOkDKrfcymU+UTQdYWOQtmfP0kt8fEBHSgggSwch/5Hhjtdjewssn1g2aja8WSNMdLfxQ4ukAyxfTIoSgdSfbuNjaeTLsVsqK4WUmsqOQDohwkQOurnqfnDQcQ015Mv9+QIjQpVS+g8iXS1QnK8lU1YBMZ83hnCi7megyQp3kT+IT56hRrbW7+XRpNECzTJ95q90BDdLDknTFiGR8tv2pv5yq+Tg2ndwaMeBrGC3XqrTIvPYSHmL2lXmROF+O6yQUW8RXEjPBCKNNRpDtgskLaFMFa1fB0sqUijtskaJStBsIZGuW+h5Vm5hgIlDuyoXNR+PHVGDwrBwWphszw8BjeQ/cjIP5ClFEOOqXwkiuSnRNoljusWc9+y3Ap4OSxVIeawgYS+Efl2QG86GHKqdt/3mzKVTi/Vbawnm+zHlp6ml5lBsvkZUqxxHghuX41Shxr/4dPc6Od4k=
  - secure: fYmAogcwHHZOmS0TPw+a2yTAG/GdvVhMrJ66GvFlyXNrOWviwqMjXtlKN9yc/4cnd/9DP7BhHmDETEApmETWx2R3B6GQ89LMbvDUQ/Cehk6R8IZVB2i0s8roO//Cv0QErNIF+Qs4qRiQ9c66OvN6nUrOzJHKrZtzKtuAQF5X0gvnebxEIQ2dMxgN9MK5UbzyYE9SEQSp5E7NLMemVhr0Rwv0yYihR0tKBG1Oez7KMRaqn/bST6fVbx6TGhAilGgKmFMNWrOEgp9VaiDuLf34YbpgXOCxYjEPV356VyauNc3Xp/OtRJr6Br7q149p5qYM+qm0HI614Eb4QrWSR6hlbukCYiCQmg/xEkitATs+DcLk0/Rkyaxa8iLjs+LNuFHhTTVvxPsbKCz6ynrhEtftAcHKvYCjuJoxyuCN9U6d4NG/GTm16GasAD17dq30KYL1MFp4X+5dcHs3FQkB9rRVsU+1TosPSoSwr4D5VzPwf8sW88WGkVKKGE7Nq6RfJLvr0kXXcZ1ct5q22vyNARw5gqBIld1L22j3+kgnx+X5CwHM7Rt6NlGsbKbVwpvFmBQ5c3glcRdSPeq4sf4TDs8HVgHM8GBh8i2G7db/3wsd73ipLADPTaoZNqJcaF6ITsfZFhoDNNxe0CGEu8NuuzQPQTmc8lLftBVC3xe+yleJMLc=
  - secure: ByA52Apy0LNMi0BzIZyxKRNuA8oJKjCi1yUOtjfWdqpKglV1QhPOsCPSnyC+QkcKRVI2YH5frOjmG4zCaNOnPGV4vudbWvH76+A4mZx/hzJCXFMaMcoF5oUcLUkhWMpvPU84NSAOV8UUKJ8ISlErX/JTjZMFrGDGKikAnOEFeiPbGsKMY4UHyzgj5dZpTs8iOP+M+zmdphxuZKNsrAT3u978e76s4xn0jkPxNG+ZNkK6RY7/NMA39Pr3QeFDEAu8w3h/eXO6Yu7lpGBx5V+Dkt4LnZh7SgE9RBVK6uydzTJVswtdKIXxNBcpAVCx+9ew1alzMDnRAAtzlql7oSYK0CADuoBIzvYczOzIiN4gKI7gpbV1W0RUReqi5Ckic1UKc8PF1sNCNNJbWuHg92KL875qlJex/IIIKC0B4Jhdd+CS8ASYNX0M9XiOKSmTrFSvh1ueJrolhXrVZw8ngIcNPkhr3Gbfi05Gyk9Y67bTRxz0AUlQYquY9lKm+h/i4RDZKL0jfRbe0mxmjAyFhilc/jbcc6piQBlVjGP9EikSNZjAFUdVg2d5MXv5VrNlPOCF6RVYvFKXz3TrkrJfa8panhIh8hNmSwWqDOjmmJ/1h9QOX3oNlvqwO06Bsf6XOY5T3y8uCDDkrg2yeAFMMPC+RzVWAa/+o9fMPz0F1CSOecQ=
  - secure: wPP3iuCgOcvdjRy6T6MIkIcN1LUZyMD5fJ++sbyXVhwyAAbtFjKLABnyqkM26Uan1YkwhUyoKKI2H3d47/tdg3rgMNcJQoUA+sUUfhhhGnBXuKMeB4FSVujmyxKQM4OYUjyJP/rdE0U487RskwOkMmDdHQjSan60l0JIGFi7eFNDJkdt76QpFw00hbb4PvbgoXJKtaSFhs5mQ+vm1gbeMc/goP4Idxwm0ukcK/wutJJgZoX48cb8bv36rAOl4GWXNHPNAkBMTA0+YEFI1a+4BUQ3KQemHNH+1LCmoFy4WF3bxtT+wxJg/+at0Nt1MJhwjtZL6eBX3rud7B9JuNO0WCXMqXUfmhhDI7WuqcHEvjUeMHA1Y0+vmbgQtOb8XU7xuWauV3yUkRKocN7eYRajE2p2/02QjIdvnyyFDOw+5+OuzQqMbXJrc2XWdXxcFIc57l5Wvxh0wThY4DS7J5nV9IHtLkA5aPX/6FD4lDSW2fZl5kwCLVfdPPLUStvG2mAAHJo4FUR5i39PTwh0k9idMInkWMjz8TRAsdPwquG6JRDDK+e0rlCbEU+Vtq2AKify5+chSQ/ylr6EDrKXTyT+bGhCjt66dplPzsAVay5q9muuLMmCNg1rSfaCzP6k8CTBXemFviqL4zWRAOsJ+/CCaOCb8xyOXJuFJqm59t8n3l4=
  - secure: nYz0zzd0Fe+AQkkVwYx+TTAEGpUFYTshEnJETfGpKyxpXxYt4Rl0nNeq7jOy1OoNnEUXDcrWv9XiYDS6L47q1c6+G3R1baOIqsg8sEnHU0cw3ogRUHIwN+HRYWBpzWUJpUL+bwa8T3pfuazUdePxJJDI+b6kxZ69ydvsS6Z7AXGWxgpEDFciZoEV1EbcJ43AchXhQvAAUyKIDq98XdHYvWMCzcEuTZ+suBIsdPBSfWbLMxbGQ17G11KnbT9IhG3ZDoYb0oBnUkDw4dConrMoGm3fBGvSUYk3izEMjebfmicLHJ1/xTOwlMPVHkUnS9bq0SPBsRxC9RWvX8sxUPuZ5gnEtOWMB96WqbZbaMeKoOv8BYLs5lVItjsHak+kIXazv4NUs8F5j6+a/sCPDzNh26RFj21rc6l6O2itB86wF0GUnEsSLdkYZhLhkSWVMoGcy5BedOogHGUo9rB+HOHbn14bM/Pr9Gf0RqWFAb3wAgmP30bX4K9QXpd4kT0HCqZHdSx82q399UDFR7LjFoojyZgKJKfKKnNnBcrvw5HjOOfcscnH3jgWG9G6Jgch6XxmeZrG2pZiJqcNkWWRuT3XulcNehgwtN06tt1abWH9KFRRMGjBAg46RsZOevXdi56/JWbsHL2X/GH2GikYURFnXLeEHmbtHF7STKkABLKEjyQ=
  - secure: SaadL9+3CxVie/JGOb5koSPXcZ1QQL299u6QESbY1JxH45SMsUMXphkfiWPkjCBYa8JIMDGD4isV2rmHUc54TU1+T/4qDqquMGPufgN4n9TiG44kmfprEXasHK/49gT/4JV1rokU7j+kkDAh4tDB/Mijs/k/XkL7eP/hQ1X5+crJ3nV6dsSpNVdyuZYQ3v9+s/IvcM6lpny46gPirNALDMliz+Jk/KCckJsObjc6gdqMq+A4yCOlgIZ7Hkcq3Q/lVTb+FIHaz5qZ9aRrEidLr8sNxdioI6XWtEqMulh/15dHApzeDoGlYS3gu6183PaKnZPJYB0gjTjOImqM/klGC5he8d2fv5pd2fLrQeG+9FEBa+emiXCuxWuFB/boTZeQdvIPeUKFBa6tirGwnphteuqbicJZHGqGECkd+n4GbhwTdwIxJGA1RvFTSvhZKrpFkxk6QOHibZXetZqG+DZzA+s4Hsv8zkwMgXoNbGHSYFgAqe+zD6QRTY2fw11r/f76Xv79OTBGA806cpIbPgOa3W5aX2G4dP1gKFUDKGvbV3PJMI938jBFf7Ng7H1gE4503bsMhq5lvtLvtkKwvMbXQPdguEZaTmDhFWW/vfaqNnyZ/YctOUMS6ZUuYv6sNndFVhTeuwCZi9DoWw1cMIsvS+FCvBBssDrt7rvGhMR4SxU=
before_script:
- chmod -R ug+x .travis
jobs:
  include:
  - stage: test
    name: Build
    script: ".travis/build.sh"
  - stage: deploy
    name: Deploy Snapshot
    if: |
      branch = master AND \
      type = push
    script: ".travis/deploy.sh"
  - stage: deploy
    name: Deploy Release
    if: tag IS present AND tag =~ ^(\d)+\.(\d)+(\.(\d)+)*(-[\w]+)*$
    script: ".travis/deploy.sh"
    deploy:
      provider: releases
      api_key:
        secure: NGgfNanpcGbJlbYaHlmhjc/ptapL4akcN49Q+b4A2/WoAIhUYItTbhRh+zwHgKpU2OE+XmV4CCL3etp9Xor2vTzmz0CmPZrhUUA3+71J8jYhgEfvchmEdA2D/jR4B0ufoDO+kWMkKORnOsIT6kElc4JOra4RIJFnlKBLrAsA2G/1dLemNG10obvdbrQ6O9t/pY7thLcbTLMUhYUQNnEtr9lVC2DM+thNUV+Yx890xJ+Nm6khE8i7rTkDPNrBAjkrNgX5gBzt3h10RIdtQlQgVnEEUbgY2jbEQBqv777XtltIudJLAdX7mOyvRWujm9nlWubJvSKo/aKhWKmXXAj1tGPbezeg6od7WuKn3RxG7kO1Z9fuptHWp/sLYGJgXLOAm/19Zj6XgEO00KRYW+zSf/MSaqEElkgKEHr2vaE7LrIb34PB8+Ra7O2tusTfCSh3vE3R9Qt1mtIT+JRAGhayni3xg2T2+HCvIQoA+W2pBRkJdV3Z+ym45lM7srdBjblAf3JMknRgwPxRIXFJiQTvjeCnjl+AQ4bcv0ntpuGQyBL4c7+ci5xus+pmVUt+dUOwQw8xmKCFXeL4LKxsDz+rWPuM+KqYS7lb+6R8QZK43S2aSsV9taCwthILjhPlJwkjFj6BYu54V6zZVj5NmybkO5fUPW0xE3KculGebsXwCbk=
      file_glob: true
      file:
        - "$TRAVIS_BUILD_DIR/jcv-db-core/build/libs/*"
        - "$TRAVIS_BUILD_DIR/jcv-db-assertj-db/build/libs/*"
        - "$TRAVIS_BUILD_DIR/jcv-db-cassandra/build/libs/*"
        - "$TRAVIS_BUILD_DIR/jcv-db-jdbc/build/libs/*"
        - "$TRAVIS_BUILD_DIR/jcv-db-mongo/build/libs/*"
      body: Release of $TRAVIS_TAG
      skip_cleanup: true
      draft: true
      on:
        repo: ekino/jcv-db
        tags: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"